import type { SearchColumn, FormFieldConfig, ContractData } from '../types';
import { ThirdPartyPlatformField, DiscoverySystemField, NclClauseField, DamagesField } from '../components/ContractFormWidgets';

export const tocSections = [
    { id: 'contract-target', label: '合約標的' },
    { id: 'registration-info', label: '造冊資訊' },
    { id: 'termination-info', label: '解約' },
    { id: 'basic-info', label: '基本資料' },
    { id: 'rights-info', label: '權利內容' },
    { id: 'royalty-info', label: '權利金比例' },
    { id: 'scope-info', label: '授權範圍' },
    { id: 'other-clauses', label: '其他條款' },
    { id: 'remittance-info', label: '匯款資料' },
    { id: 'scan-file', label: '合約掃描檔' },
    { id: 'remarks', label: '備註' },
];

export const authorizationFormOptions = { 
    '非專': ['L4', 'L4臺大方案一', 'L5-1', 'L5-1臺大方案二', 'L5', 'L5臺大方案三'],
    '專屬': ['L1', 'L3'],
    '獨家': ['L2'],
    '共出編輯': [],
    '共同出版': [],
    '亞東專屬': []
};

export const discoveryPlatforms = ['Google Scholar', 'NAVER Academic', 'Primo', 'EBSCO EDS', 'OCLC Discovery'];
export const embargoTargets = ['第三方平台', '國家圖書館', 'TOAJ'];
export const embargoPeriods = ['一年', '半年', '一期'];

export const defaultSearchColumns: SearchColumn[] = [
  { id: 'title', name: '刊名', isDefault: true },
  { id: 'managementNo', name: '管理編號', isDefault: true },
];

// --- 新增 fieldConfig ---
export const fieldConfig: { [sectionId: string]: FormFieldConfig[] } = {
    'contract-target': [
        { id: 'publicationId', label: 'PublicationID', type: 'text' },
        { id: 'type', label: '類型', type: 'text' },
        { id: 'title', label: '刊名', type: 'text' },
        { id: 'volumeInfo', label: '起始卷期', type: 'text' },
        { id: 'issnIsbn', label: 'ISSN/ISBN', type: 'text' },
    ],
    'registration-info': [
        { id: 'isCurrent', label: '現行合約', type: 'radio', options: ['是', '否'] },
        { id: 'managementNo', label: '管理部編號', type: 'text' },
        { id: 'departmentNo', label: '學發合約編號', type: 'text' },
        { id: 'departmentSubNo', label: '學發合約子編號', type: 'text' },
        { id: 'collector', label: '負責徵集', type: 'text' },
        { id: 'asResponsible', label: '負責AS', type: 'text' },
        { id: 'contractVersion', label: '合約版本', type: 'tags', fullWidth: true },
        { id: 'nonAiritiVersion', label: '非華藝版本號', type: 'text', fullWidth: true },
    ],
    'basic-info': [
        { id: 'contractParty', label: '簽約單位', type: 'tags', fullWidth: true, placeholder: "新增單位後按 Enter..." },
        { id: 'partyARep', label: '甲方簽約代表', type: 'text', fullWidth: true },
        { id: 'partyBRep', label: '乙方簽約代表', type: 'text' },
        { id: 'contractStartDate', label: '合約起日', type: 'date' },
        { id: 'contractEndDate', label: '合約迄日', type: 'date' },
        { id: 'autoRenew', label: '自動續約', type: 'group', fields: [
            { id: 'autoRenewYears', label: '自動續約___年', type: 'text' },
            { id: 'autoRenewFrequency', label: '每___年續 einmal', type: 'text' },
        ]},
        { id: 'thereafter', label: '其後亦同', type: 'radio', options: ['是', '否'] },
        { id: 'specialDateInfo', label: '特殊年限資訊', type: 'text', fullWidth: true },
    ],
    'rights-info': [
        { id: 'authorizationForm', label: '授權形式', type: 'cascading-select', options: authorizationFormOptions, fullWidth: true },
        { id: 'paymentType', label: '有償_無償', type: 'radio', options: ['有償', '無償'] },
        { id: 'isOpenAccess', label: 'OA', type: 'radio', options: ['有', '無'] },
    ],
    'scope-info': [
        { id: 'thirdPartyPlatform', label: '第三方平台', type: 'custom', component: ThirdPartyPlatformField, fullWidth: true },
        { id: 'discoverySystem', label: '國際第三方發現系統或平台', type: 'custom', component: DiscoverySystemField, fullWidth: true },
        { id: 'comparisonSystem', label: '比對系統', type: 'radio', options: ['是', '否'] },
        { id: 'nclClause', label: '不上國圖條文｜第三方平台', type: 'custom', component: NclClauseField, fullWidth: true },
        { id: 'listingLocation', label: '上架位置', type: 'radio', options: ['全球用戶', '不上CN', '不上CN含港澳'] },
        { id: 'status_al_cn', label: '不上AL_CN_現行狀況', type: 'text', fullWidth: true },
    ],
    'other-clauses': [
        { id: 'usageRightsWarranty', label: '甲方義務_甲方保証有使用權利', type: 'select', options: ['保證+甲方賠償', '保證+甲方不賠', '未保證'] },
        { id: 'userRightsProtection', label: '用戶權益保障', type: 'radio', options: ['是', '否'] },
        { id: 'terminationClause', label: '合約終止_書目更動_終止條文', type: 'radio', options: ['是', '否'] },
        { id: 'forceMajeure', label: '不可抗力條款', type: 'radio', options: ['是', '否'] },
        { id: 'confidentiality', label: '保密條款', type: 'radio', options: ['是', '否'] },
        { id: 'noOaOnOwnWebsite', label: '自有網站不OA條文', type: 'radio', options: ['是', '否'] },
        { id: 'legalIssueHandling', label: '法律問題處理', type: 'select', options: ['甲方', '乙方', '雙方', '法律解決'] },
        { id: 'manuscriptAgreementMention', label: '甲方義務_稿約明文規定', type: 'radio', options: ['是', '否'] },
        { id: 'authorizationCopy', label: '甲方義務_收授權書_影本', type: 'radio', options: ['是', '否'] },
        { id: 'damages', label: '損害賠償', type: 'custom', component: DamagesField, fullWidth: true },
    ],
    'remittance-info': [
        { id: 'beneficiary', label: '分潤主體', type: 'text', fullWidth: true, isReadOnly: true },
        { id: 'accountType', label: '帳戶類別', type: 'radio', options: ['國內', '國外'] },
        { id: 'accountName', label: '戶名', type: 'text' },
        { id: 'checkTitle', label: '支票抬頭', type: 'text' },
        { id: 'currency', label: '幣別', type: 'text' },
        { id: 'bankName', label: '銀行名稱', type: 'text' },
        { id: 'branchName', label: '分行名稱', type: 'text' },
        { id: 'accountNumber', label: '銀行帳號', type: 'text' },
        { id: 'accountNotes', label: '帳務備註', type: 'textarea', fullWidth: true },
        { id: 'taxId', label: '統一編號', type: 'text' },
        { id: 'idNumber', label: '身分證字號', type: 'text' },
        { id: 'royaltySettlementMonth', label: '版稅結算月份', type: 'text' },
        { id: 'paymentReceiptFlow', label: '收付款流程', type: 'text' },
    ],
    'termination-info': [
        { id: 'isTerminated', label: '解約', type: 'radio', options: ['是', '否'] },
        { id: 'terminationReason', label: '解約原因', type: 'text', condition: (formData: ContractData) => formData.terminationInfo?.isTerminated === '是' },
        { id: 'terminationDate', label: '解約日期', type: 'date', condition: (formData: ContractData) => formData.terminationInfo?.isTerminated === '是' },
        { id: 'terminationMethod', label: '解約方式', type: 'text', condition: (formData: ContractData) => formData.terminationInfo?.isTerminated === '是' },
    ],
    'remarks': [
        { id: 'remarks', label: '', type: 'textarea' },
    ]
};

// --- 圖服部專用設定 (從 TuFuFields 移植) ---

export const tuFuTocSections = [
    { id: 'registration-info', label: '造冊資訊' },
    { id: 'basic-info', label: '基本資料' },
    { id: 'rights-info', label: '[電子書]書籍基本權利' },
    { id: 'scope-info', label: '[電子書]2B銷售權利' },
    { id: 'other-clauses', label: '[電子書]2C銷售權利' },
    { id: 'accounting-info', label: '[電子書]帳務相關資訊' },
    { id: 'tw-book-rights', label: '[台版書]基本權利' },
    { id: 'tw-book-accounting', label: '[台版書]採購/帳務相關' },
    { id: 'tw-book-logistics', label: '[台版書]採購/集貨相關' },
    { id: 'tw-book-contact', label: '[台版書]窗口資訊' },
    { id: 'scan-file', label: '合約掃描檔' },
    { id: 'remarks', label: '備註' },
];

export const fieldKeyToNameMap: { [key: string]: string } = {
    'registrationInfo.airitiContractNo': '華藝合約編號',
    'registrationInfo.ebookContractNo': '【圖服部】合約編號',
    'registrationInfo.acquisitionMaintainer': '徵集維護人員',
    'registrationInfo.asTeamMaintainer': 'as組維護人員',
    'basicInfo.publisherName': '出版單位名稱',
    'basicInfo.licensorPersonInCharge': '授權方負責人',
    'basicInfo.licensorRep': '授權方簽約代表',
    'basicInfo.airitiSignatory': '華藝簽約人員',
    'basicInfo.contractTargetType': '合約標的類型',
    'basicInfo.contractStatus': '合作中',
    'basicInfo.earlyTermination': '提前解約',
    'basicInfo.contractStartDate': '合約起日',
    'basicInfo.contractEndDate': '合約迄日',
    'basicInfo.autoRenewYears': '自動續約年',
    'basicInfo.autoRenewTimes': '自動續約次數',
    'basicInfo.thereafter': '其後亦同',
    'basicInfo.contractVersionNo': '合約版本號',
    'basicInfo.contractName': '合約名稱',
    'basicInfo.specialPenalties': '出版社自訂特殊罰責',
    'basicInfo.jurisdiction': '管轄法院',
    'rightsInfo.trialPercentage': '試閱%',
    'rightsInfo.printingPercentage': '列印%',
    'rightsInfo.fullTextDigitization': '全文數位化',
    'rightsInfo.trialAccess': '試用權限',
    'rightsInfo.tts': 'TTS',
    'rightsInfo.fullTextSearch': '全文檢索',
    'rightsInfo.dataComparison': '資料比對',
    'rightsInfo.systemData': '系統資料擷取',
    'rightsInfo.captureAnalysisProcessing': '分析處理',
    'rightsInfo.autoGeneration': '自動生成',
    'rightsInfo.algorithmTraining': '演算訓練',
    'rightsInfo.languageSwitching': '語言切換',
    'rightsInfo.chapterPresentation': '分篇呈現',
    'rightsInfo.chapterSales': '分篇銷售',
    'rightsInfo.marketingModel': '行銷模式',
    'rightsInfo.publisherSpecs': '甲方出版品規格',
    'rightsInfo.doiApplication': 'DOI申請',
    'rightsInfo.doiFee': 'DOI費用NTD(筆)',
    'rightsInfo.thirdPartyAuthorization': '第三方授權',
    'rightsInfo.thirdPartyConsignment': '第三方代銷',
    'rightsInfo.salesChannels': '銷售通路',
    'rightsInfo.paymentMethodRights': '收費方式',
    'rightsInfo.listingSchedule': '上架排程',
    'rightsInfo.listingItems': '上架品項',
    'rightsInfo.listingPlatforms': '上架平台',
    'rightsInfo.tradingConditions': '交易條件',
    'rightsInfo.contentPresentation': '呈現內容',
    'rightsInfo.serviceModel': '服務模式',
    'scopeInfo.b2bSalesRightsToggle': 'B2B銷售權利',
    'scopeInfo.b2bAuthorizationType': 'B2B授權類型',
    'scopeInfo.b2bSplitPercentage': 'B2B拆帳%',
    'scopeInfo.b2bSalesRegion': 'B2B銷售地區',
    'scopeInfo.b2bMinMultiple': 'B2B約定最低倍數',
    'scopeInfo.b2bRoyaltyAdjustment': 'B2B權利金底價強制調整倍數必要性',
    'scopeInfo.b2bPricingPower': 'B2B價格決定權',
    'scopeInfo.b2bLease': 'B2B租賃',
    'scopeInfo.b2bBuyout': 'B2B買斷',
    'scopeInfo.b2bPayPerUse': 'B2B依次計費',
    'scopeInfo.b2bPda': 'B2BPDA',
    'scopeInfo.b2bAlliance': 'B2B聯盟',
    'scopeInfo.b2bPublicTender': 'B2B公開標案',
    'scopeInfo.b2bRestrictiveTender': 'B2B限制性招標案',
    'scopeInfo.subscription': '訂閱',
    'scopeInfo.eLibrarySalesRight': '電子館合銷售權利',
    'scopeInfo.eLibraryContractType': '電子館合合約類型',
    'scopeInfo.eLibrarySplit': '電子館合拆帳',
    'scopeInfo.eLibraryPricing': '電子館合定價',
    'otherClauses.b2cSalesRightsToggle': 'B2C銷售權利',
    'otherClauses.b2cAuthorizationType': 'B2C授權類型',
    'otherClauses.b2cSplitPercentage': 'B2C拆帳%',
    'otherClauses.b2cSalesRegion': 'B2C銷售地區',
    'otherClauses.b2cQuotationPrinciple': 'B2C約定報價原則',
    'otherClauses.b2cRoyaltyAdjustment': 'B2C權利金底價強制調整倍數必要性',
    'otherClauses.b2cPricingPower': 'B2C價格決定權',
    'otherClauses.b2cLease': 'B2C租賃',
    'otherClauses.b2cBuyout': 'B2C買断',
    'otherClauses.b2cPayPerUse': 'B2C依次計費',
    'otherClauses.b2cVariablePriceAuth': 'B2C變價活動需逐案取得授權方同意',
    'otherClauses.shuNiuXiong': '灰熊',
    'otherClauses.kingstone': '金石堂',
    'otherClauses.sanmin': '三民',
    'otherClauses.taaze': '讀冊',
    'otherClauses.trmsSalesRightsToggle': 'TRMS銷售權利',
    'otherClauses.trmsSplitPercentage': 'TRMS拆帳%',
    'otherClauses.distributorPlatformToggle': '經銷平台上架權',
    'otherClauses.distributorSplit': '經銷拆帳%',
    'otherClauses.cannotListPlatforms': '不得上架平台',
    'otherClauses.amazon': 'Amazon',
    'otherClauses.google': 'Google',
    'otherClauses.kobo': 'Kobo',
    'otherClauses.pubu': 'Pubu',
    'otherClauses.eslite': '誠品(Pubu串接)',
    'otherClauses.pchome': 'PCHOME(Pubu串接)',
    'otherClauses.readmoo': 'Readmoo',
    'otherClauses.udn': 'UDN',
    'otherClauses.bookwalker': '台灣漫讀BOOKWALKER',
    'otherClauses.hyweb': '凌網',
    'otherClauses.bookscom': '博客來',
    'otherClauses.apple': 'Apple',
    'otherClauses.mybook': 'Mybook',
    'otherClauses.momo': 'MOMO',
    'otherClauses.twb': 'TWB',
    'otherClauses.hkUe': '香港聯合電子',
    'otherClauses.ingram': 'Ingram',
    'otherClauses.overdrive': 'Overdrive',
    'otherClauses.hami': 'Hami',
    'otherClauses.truth': '恩道',
    'otherClauses.wechat': '微信',
    'accountingInfo.entityType': '公/私/個人',
    'accountingInfo.locationType': '國內/國外單位',
    'accountingInfo.billingCycle': '結帳週期',
    'accountingInfo.paymentTerm': '匯款期限或票期',
    'accountingInfo.paymentMethod': '支付方式',
    'accountingInfo.accountHolderName': '戶名/抬頭',
    'accountingInfo.taxId': '統編',
    'accountingInfo.idNumber': '身分證字號',
    'accountingInfo.bankName': '銀行',
    'accountingInfo.bankCode': '銀行代碼',
    'accountingInfo.branchName': '分行',
    'accountingInfo.branchCode': '分行代碼',
    'accountingInfo.accountNumber': '帳號',
    'accountingInfo.swiftCode': 'SWIFT Code',
    'accountingInfo.bankAddress': '銀行地址',
    'accountingInfo.remittanceNotes': '備註',
    'twBookRights.exclusiveAuthorization': '專屬授權/非專屬授權',
    'twBookRights.exclusiveConditions': '專屬條件/範圍/備註',
    'twBookRights.trialTwBook': '試閱',
    'twBookRights.fullTextDigitizationTwBook': '全文數位化',
    'twBookAccounting.twBookOverseasDiscount': '台版書海外供貨折扣(含稅)',
    'twBookAccounting.twBookBillingCycle': '對帳週期',
    'twBookAccounting.twBookPaymentMethod': '貨款付款方式',
    'twBookAccounting.twBookPaymentTerms': '貨款支付時間(票期)',
    'twBookAccounting.twBookAccountHolder': '戶名/抬頭',
    'twBookAccounting.twBookPayeeInfo': '收款單位',
    'twBookAccounting.twBookBankName': '銀行名稱',
    'twBookAccounting.twBookBranchName': '分行/支局',
    'twBookAccounting.twBookAccountNumber': '帳號',
    'twBookLogistics.minimumShipmentThreshold': '最低出貨門檻',
    'twBookLogistics.freeShippingThreshold': '免運費出貨門檻',
    'twBookLogistics.returnCycle': '退貨週期',
    'twBookLogistics.nonDefectiveReturnShippingFee': '非瑕疵書退貨運費支付認定',
    'twBookLogistics.domesticReturnShippingFee': '國內退貨運費支付認定',
    'twBookLogistics.sampleBookDiscount': '樣書折扣(含稅)',
    'twBookLogistics.sampleBookBillingCycle': '樣書結帳週期',
    'twBookLogistics.authorizedSalesRegion': '授權銷售地區',
    'twBookLogistics.subDistribution': '轉代理銷售',
    'twBookContact.publisherRegion': '出版單位地區',
    'twBookContact.contactPersonInfo': '聯絡人姓名/單位',
    'twBookContact.contactPersonTitle': '聯絡人職位',
    'twBookContact.contactPersonEmail': '聯絡人信箱',
    'twBookContact.contactPersonPhone': '聯絡人電話',
    'twBookContact.companyAddress': '公司地址',
    'twBookContact.logisticsAddress': '集貨地址',
    'remarks': '備註',
    'scanFile': '合約掃描檔',
};

export const dropdownOptions: { [key: string]: { value: string; label: string }[] } = {
    'basicInfo.contractTargetType': [
        {value: 'ebook', label: '電子書'}, 
        {value: 'ejournal', label: '電子雜誌'}, 
        {value: 'taiwaneseBook', label: '台版書'}
    ],
    'accountingInfo.entityType': [
        {value: 'public', label: '公部門'},
        {value: 'private', label: '私部門'},
        {value: 'individual', label: '個人'}
    ],
    'twBookAccounting.twBookBillingCycle': [
        {value: 'cash', label: '付現'},
        {value: 'monthly', label: '月結'},
        {value: 'quarterly', label: '季結'},
        {value: 'semi_annually', label: '半年結'},
        {value: 'annually', label: '年結'}
    ],
    'twBookLogistics.returnCycle': [{value: 'semi_annually', label: '每半年退貨一次'}, {value: 'non_returnable', label: '不可退貨'}],
    'twBookLogistics.nonDefectiveReturnShippingFee': [{value: 'airiti', label: '華藝支付'}, {value: 'publisher', label: '出版社支付'}, {value: 'non_returnable', label: '不可退貨'}],
    'twBookLogistics.domesticReturnShippingFee': [{value: 'airiti', label: '華藝支付'}, {value: 'publisher', label: '出版社支付'}, {value: 'non_returnable', label: '不可退貨'}],
};

export const radioOptions: { [key: string]: {value: string, label: string}[] } = {
    'basicInfo.contractStatus': [{value: 'yes', label: '是'}, {value: 'no', label: '否'}],
    'basicInfo.earlyTermination': [{value: 'yes', label: '是'}, {value: 'no', label: '否'}],
    'accountingInfo.locationType': [{value: 'domestic', label: '國內單位'}, {value: 'international', label: '國外單位'}],
    'basicInfo.thereafter': [{value: 'yes', label: '是'}, {value: 'no', label: '否'}],
    'scopeInfo.b2bSalesRightsToggle': [{value: 'yes', label: '是'}, {value: 'no', label: '否'}, {value: 'by_title', label: 'by title'}],
    'scopeInfo.b2bRoyaltyAdjustment': [{value: 'yes', label: '是'}, {value: 'no', label: '否'}],
    'scopeInfo.b2bPricingPower': [{value: 'yes', label: '是'}, {value: 'no', label: '否'}],
    'scopeInfo.subscription': [{value: 'yes', label: '是'}, {value: 'no', label: '否'}],
    'scopeInfo.eLibrarySalesRight': [{value: 'yes', label: '是'}, {value: 'no', label: '否'}],
    'otherClauses.b2cSalesRightsToggle': [{value: 'yes', label: '是'}, {value: 'no', label: '否'}, {value: 'by_title', label: 'by title'}],
    'otherClauses.b2cRoyaltyAdjustment': [{value: 'yes', label: '是'}, {value: 'no', label: '否'}],
    'otherClauses.b2cPricingPower': [{value: 'yes', label: '是'}, {value: 'no', label: '否'}],
    'otherClauses.trmsSalesRightsToggle': [{value: 'yes', label: '是'}, {value: 'no', label: '否'}, {value: 'by_title', label: 'by title'}],
    'otherClauses.distributorPlatformToggle': [{value: 'yes', label: '是'}, {value: 'no', label: '否'}, {value: 'by_title', label: 'by title'}],
    'twBookRights.exclusiveAuthorization': [{value: 'exclusive', label: '專屬'}, {value: 'non_exclusive', label: '非專屬'}],
    'twBookRights.fullTextDigitizationTwBook': [{value: 'yes', label: '是'}, {value: 'no', label: '否'}],
    'twBookAccounting.twBookPaymentMethod': [{value: 'remittance', label: '匯款'}, {value: 'check', label: '支票'}, {value: 'other', label: '其他'}],
    'twBookAccounting.twBookPayeeInfo': [{value: 'remittance', label: '銀行'}, {value: 'check', label: '郵局'}, { value: 'prepayment', label: '預付款' }],
    'twBookLogistics.subDistribution': [{value: 'yes', label: '是'}, {value: 'no', label: '否'}],
    'twBookContact.publisherRegion': [{value: 'domestic', label: '國內'}, {value: 'overseas', label: '海外'}],
};

export const checkboxOptions: { [key: string]: { key: string; label: string }[] } = {};

export const validationRules = {
  hard: [
    'registrationInfo.airitiContractNo',
    'registrationInfo.ebookContractNo',
    'registrationInfo.acquisitionMaintainer',
    'basicInfo.earlyTermination',
    'basicInfo.publisherName',
    'basicInfo.contractStartDate',
    'basicInfo.contractEndDate',
    'basicInfo.thereafter',
    'basicInfo.contractVersionNo',
    'basicInfo.contractName',
  ],
};